/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba2;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author moises
 */
public class MenuResultados extends javax.swing.JFrame {
    
    private String VelocidadInsta;
    private String Anguloinsta;
    private String DistanciaRecorrida;
    private String alturainsta;
    private String distanciaMax;
    private String EnergiaCine;
    private String aluraMax;
    private String EnergiaPO;
    private String TrabajoViento;
    private String EnergiaMeca;

    public String getVelocidadInsta() {
        return VelocidadInsta;
    }

    public void setVelocidadInsta(String VelocidadInsta) {
        this.VelocidadInsta = VelocidadInsta;
    }

    public String getAnguloinsta() {
        return Anguloinsta;
    }

    public void setAnguloinsta(String Anguloinsta) {
        this.Anguloinsta = Anguloinsta;
    }

    public String getDistanciaRecorrida() {
        return DistanciaRecorrida;
    }

    public void setDistanciaRecorrida(String DistanciaRecorrida) {
        this.DistanciaRecorrida = DistanciaRecorrida;
    }

    public String getAlturainsta() {
        return alturainsta;
    }

    public void setAlturainsta(String alturainsta) {
        this.alturainsta = alturainsta;
    }

    public String getDistanciaMax() {
        return distanciaMax;
    }

    public void setDistanciaMax(String distanciaMax) {
        this.distanciaMax = distanciaMax;
    }

    public String getEnergiaCine() {
        return EnergiaCine;
    }

    public void setEnergiaCine(String EnergiaCine) {
        this.EnergiaCine = EnergiaCine;
    }

    public String getAluraMax() {
        return aluraMax;
    }

    public void setAluraMax(String aluraMax) {
        this.aluraMax = aluraMax;
    }

    public String getEnergiaPO() {
        return EnergiaPO;
    }

    public void setEnergiaPO(String EnergiaPO) {
        this.EnergiaPO = EnergiaPO;
    }

    public String getTrabajoViento() {
        return TrabajoViento;
    }

    public void setTrabajoViento(String TrabajoViento) {
        this.TrabajoViento = TrabajoViento;
    }

    public String getEnergiaMeca() {
        return EnergiaMeca;
    }

    public void setEnergiaMeca(String EnergiaMeca) {
        this.EnergiaMeca = EnergiaMeca;
    }
    
    /**
     * Creates new form Opciones
     */
    
    public MenuResultados() {
        
        
          this.setContentPane(new MenuResultados.ImagenFondo());
          setLocation(95, 250);
          initComponents();
           setVisible(true);
          //Dibujo_Diagrama abrir = new Dibujo_Diagrama();
          //abrir.setVisible(true);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU DE RESULTADOS");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(318, 579));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU DE RESULTADOS");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 6, 212, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSTANTANEO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 140, 90, 16);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("POTENCIAL Y MECANICA");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(100, 420, 150, 16);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ALTURA");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(110, 350, 90, 16);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("MAXIMA");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(180, 350, 90, 16);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VECTOR FUERZA VIENTO");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(100, 490, 160, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MAXIMA");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 330, 90, 16);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("TRABAJO REALIZADO POR");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(110, 470, 160, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ENERGIA CINETICA,");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 400, 120, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INSTANTANEA");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 280, 90, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ALTURA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 260, 60, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSTANTANEA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 70, 90, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EN EL TIEMPO DADO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 210, 119, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DISTANCIA");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(110, 330, 90, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ANGULO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 120, 60, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DISTANCIA RECORRIDA ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 190, 160, 16);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VELOCIDAD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 50, 90, 16);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 460, 240, 60);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 180, 240, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 40, 240, 60);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 110, 240, 60);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 250, 240, 60);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 320, 240, 60);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IMAGENFONDOBUTTON.jpg"))); // NOI18N
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 390, 240, 60);

        jLabel3.setText("VELOCIDAD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 80, 16);

        pack();
    }// </editor-fold>                        

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {                                      
        JOptionPane.showMessageDialog(null, "Velociadad instantánea como vector: " + VelocidadInsta);
     
    }                                     

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {                                      
       JOptionPane.showMessageDialog(null, "Ángulo instantáneo: " + getAnguloinsta());
    }                                     

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {                                      
       JOptionPane.showMessageDialog(null, "Distancia Recorrida en el tiempo dado: "+ getDistanciaRecorrida());
    }                                     

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {                                      
       JOptionPane.showMessageDialog(null, "Áltura instantánea: " + getAlturainsta());
    }                                     

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {                                      
        JOptionPane.showMessageDialog(null, "Distancia Máxima: " + getDistanciaMax() + "\n" +
                                            "Altura Máxima: " + getAluraMax());
    }                                     

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {                                      
      JOptionPane.showMessageDialog(null, "Energia Cinéticca instantánea: " + getEnergiaCine() +"\n" +
                                          "Energia Potencial gravitatoria instantánea: " +getEnergiaPO() + "\n" +
                                          "Energia mecánica total: " +getEnergiaMeca() + "\n");
    }                                     

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {                                      
        JOptionPane.showMessageDialog(null, "Trabajo Realizado por el vector fuerza viento: " + getTrabajoViento());
    }                                     

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
public class ImagenFondo extends JPanel
{
     public void paint(Graphics g)
    {
        ImageIcon imagen = new ImageIcon(getClass().getResource("../Imagen/Fondo2.jpg"));
        g.drawImage(imagen.getImage(),0, 0,getWidth(),getHeight(), this);
        setOpaque(false);
        super.paint(g);
        
    }
}
}
