/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba2;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author moises
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        
        
          this.setContentPane(new Opciones.ImagenFondo());
          setLocation(1510, 250);
          initComponents();
          setVisible(true);
          //Dibujo_Diagrama abrir = new Dibujo_Diagrama();
          //abrir.setVisible(true);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Velocidad_Incial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Angulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Masa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Altura = new javax.swing.JTextField();
        Viento = new javax.swing.JTextField();
        Tiempo = new javax.swing.JTextField();
        Gravedad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Dibujo_Diagrama abrir = new Dibujo_Diagrama();
        MenuResultados menu = new MenuResultados();
        menu.setVisible(true);
        abrir.setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPCIONES");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VELOCIDAD INICIAL");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OPCIONES");

        Velocidad_Incial.setText("10.0");
        Velocidad_Incial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Velocidad_IncialActionPerformed(evt);
            }
        });
        Velocidad_Incial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Velocidad_IncialKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ÁNGULO INICIAL");

        Angulo.setText("65.0");
        Angulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnguloActionPerformed(evt);
            }
        });
        Angulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AnguloKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MASA DEL PROYECTIL");

        Masa.setText("0.00");
        Masa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasaActionPerformed(evt);
            }
        });
        Masa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MasaKeyTyped(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALTURA INICIAL");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VECTOR FUERZA DEL VIENTO");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TIEMPO FINAL");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GRAVEDAD");

        Altura.setText("0.00");
        Altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AlturaKeyTyped(evt);
            }
        });

        Viento.setText("0.00");
        Viento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VientoKeyTyped(evt);
            }
        });

        Tiempo.setText("0.00");
        Tiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TiempoKeyTyped(evt);
            }
        });

        Gravedad.setText("9.81");
        Gravedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravedadActionPerformed(evt);
            }
        });
        Gravedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GravedadKeyTyped(evt);
            }
        });

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Masa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Velocidad_Incial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Gravedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(Viento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Velocidad_Incial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Masa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Viento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Gravedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         
       
       
        //simulador
         Dibujo_Diagrama datos = new Dibujo_Diagrama();
         datos.setVelocidad(Double.parseDouble(Velocidad_Incial.getText()));
         datos.setAngulo(Double.parseDouble(Angulo.getText()));         
         datos.setAltura(Double.parseDouble(Altura.getText()));        
         datos.setGravedad(Double.parseDouble(Gravedad.getText()));
         datos.setMasa(Double.parseDouble(Masa.getText()));
         datos.setViento(Double.parseDouble(Viento.getText()));
         //operaciones 
         Operaciones datos2 = new Operaciones();
         datos2.setMasa(Double.parseDouble(Masa.getText()));
         datos2.setViento(Double.parseDouble(Viento.getText()));
         datos2.setTiempo(Double.parseDouble(Tiempo.getText()));
         datos2.setVelocidad(Double.parseDouble(Velocidad_Incial.getText()));
         datos2.setAngulo(Double.parseDouble(Angulo.getText()));         
         datos2.setAltura(Double.parseDouble(Altura.getText()));        
         datos2.setGravedad(Double.parseDouble(Gravedad.getText()));
         
         //Mostrar
         MenuResultados datos3 = new MenuResultados();
         datos3.setVelocidadInsta(datos2.VelocidadInstaResTiempo());
         datos3.setAnguloinsta(String.valueOf(datos2.AnguloInsta()));
         datos3.setDistanciaRecorrida(String.valueOf(datos2.DistanciaT()));
         datos3.setAlturainsta((String.valueOf(datos2.AlturaInstan())));
         datos3.setDistanciaMax((String.valueOf(datos2.DistanciaMax())));
         datos3.setAluraMax((String.valueOf(datos2.AlturaMax())));
         datos3.setEnergiaCine((String.valueOf(datos2.EnergiaCineInsta())));
         datos3.setEnergiaPO((String.valueOf(datos2.EnergiaPotencial())));
         datos3.setTrabajoViento((String.valueOf(datos2.trabajoViento())));
         datos3.setEnergiaMeca((String.valueOf(datos2.EnergiaMecanica())));
         JOptionPane.showMessageDialog(null, "Datos Procesados ");
         
    }                                        

    private void GravedadActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void MasaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void AnguloActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Velocidad_IncialActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void Velocidad_IncialKeyTyped(java.awt.event.KeyEvent evt) {                                          
            char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                                         

    private void AnguloKeyTyped(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                               

    private void MasaKeyTyped(java.awt.event.KeyEvent evt) {                              
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                             

    private void AlturaKeyTyped(java.awt.event.KeyEvent evt) {                                
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                               

    private void VientoKeyTyped(java.awt.event.KeyEvent evt) {                                
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                               

    private void TiempoKeyTyped(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                               

    private void GravedadKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
            if(Character.isLetter(validar))
            {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            }
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Opciones c = new Opciones();

    }
    // Variables declaration - do not modify                     
    private javax.swing.JTextField Altura;
    private javax.swing.JTextField Angulo;
    private javax.swing.JTextField Gravedad;
    private javax.swing.JTextField Masa;
    private javax.swing.JTextField Tiempo;
    private javax.swing.JTextField Velocidad_Incial;
    private javax.swing.JTextField Viento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration                   
public class ImagenFondo extends JPanel
{
     public void paint(Graphics g)
    {
        ImageIcon imagen = new ImageIcon(getClass().getResource("../Imagen/Fondo2.jpg"));
        g.drawImage(imagen.getImage(),0, 0,getWidth(),getHeight(), this);
        setOpaque(false);
        super.paint(g);
        
    }
}
}
